---
title: "VN Elite Network - Data Management"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(tidyverse)
library(dplyr)
library(igraph)
library(ggplot2)
```

# Elite data
```{r}
d <- rio::import(here::here("data", "po_gov.xlsx")) %>% 
  mutate(person_name = str_to_lower(person_name), 
         hometown = str_to_lower(hometown)) %>% 
  mutate(branch = ifelse(str_detect(seatID, "pol"), "Politburo", "Government")
         )   # pol = 1, gov = 0

d <- d %>% 
  mutate(year_starting_term = case_when(year_branch_term_serve == "pol96_01" ~ 1996,
                                        year_branch_term_serve == "gov97_02" ~ 1997,
                                        
                                        year_branch_term_serve == "pol01_06" ~ 2001, 
                                        year_branch_term_serve == "gov02_07" ~ 2002,
                                        
                                        year_branch_term_serve == "pol06_11" ~ 2006,
                                        year_branch_term_serve == "gov07_11" ~ 2007,
                                        
                                        term_serve == "06_011" ~ 2006,
                                        term_serve == "11_16" ~ 2011,
                                        term_serve == "16_21" ~ 2016,
                                        term_serve == "21_26" ~ 2021,
                                        )) %>% 
  
  mutate(year_to_retire = ifelse(gender == "M", year_birth + 62, year_birth + 60),
         year_working_left =  year_to_retire - year_starting_term
             ) 

#saveRDS(d, "elite_data.RDS")

# unique individuals 

d %>% 
  select(person_name) %>% distinct()
# seats and persons in politburo
d %>% 
  filter(grepl("pol.*", seatID)) %>% select(person_name) %>% distinct()


# seats and persons in politburo
d %>% 
  filter(grepl("gov.*", seatID)) %>% select(person_name) %>% distinct()
select(person_name)

# female
d %>% 
  filter(gender == "F") %>% select(person_name) %>% distinct()


```


# FDI data
2018: https://www.mpi.gov.vn/Pages/tinbai.aspx?idTin=41920&idcm=208

```{r}
fdi2013 <- import(here("data", "FDI 12.2013.xls"), sheet = 3) %>% 
  select(province = `Địa phương`,
       fdi_2013 = `Vốn đăng ký cấp mới và tăng thêm (triệu USD)`)

fdi2014 <- import(here("data", "FDI_12.2014.xls"), sheet = 3) %>% 
  select(province = `Địa phương`,
       fdi_2014 = `Vốn đăng ký cấp mới và tăng thêm (triệu USD)`)

fdi2015 <- import(here("data", "FDI 12.2015 31-12-2015 final.xls"), sheet = 3) %>% 
  select(province = `Địa phương`,
       fdi_2015 = `Vốn đăng ký cấp mới và tăng thêm (triệu USD)`) %>% 
  mutate(province = ifelse(province == "TP Hồ Chí Minh", "TP. Hồ Chí Minh", province))


fdi2016 <- import(here("data", "FDI2016.xls"), sheet = 3) %>% 
  select(province = `...2`,
       fdi_2016 = `Tổng vốn đăng ký cấp mới, vốn tăng thêm và Vốn góp (triệu USD)`)

fdi2017 <- import(here("data", "FDI_12.2017.xls"), sheet = 3) %>% 
  select(province = `Địa phương`,
       fdi_2017 = `Tổng vốn đăng ký (triệu USD)`)

fdi2018 <- import(here("data", "FDI_12.2018.xls"), sheet = 3) %>% 
  select(province = `Địa phương`,
       fdi_2018 = `Tổng vốn đăng ký (triệu USD)`)

fdi2019 <- import(here("data", "FDI_2019.xls"), sheet = 3) %>% 
  select(province = `Địa phương`,
       fdi_2019 = `Tổng vốn đăng ký (triệu USD)`)

fdi2020 <- import(here("data", "FDI_12.2020.xlsx"), sheet = 3) %>% 
  select(province = `Địa phương`, english_name,
       fdi_2020 = `Tổng vốn đăng ký (triệu USD)`)

fdi13_20 <- fdi2013 %>% 
  full_join(fdi2014) %>% 
    mutate(province = ifelse(province == "TP Hồ Chí Minh", "TP. Hồ Chí Minh", province),
           province = ifelse(province == "Bà Rịa-Vũng Tàu", "Bà Rịa - Vũng Tàu", province),
           province = ifelse(province == "Đắc Lắc", "Đăk Lăk", province),
           province = ifelse(province == "Thừa Thiên-Huế", "Thừa Thiên Huế", province)) %>% 
  full_join(fdi2015) %>% 
  full_join(fdi2016) %>% 
  full_join(fdi2017) %>% 
  full_join(fdi2018) %>% 
  full_join(fdi2019) %>% 
  full_join(fdi2020) %>% # hand typed english name of provinces in fdi2020 to join with elite data
  drop_na(province) %>% 
  filter(province != "Dầu khí") %>% select(-province) %>% 
  rename(hometown = english_name)

#saveRDS(fdi13_20, "fdi13_20.RDS")

fdi13_20
```

