---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://solomonmg.github.io/post/working-with-bipartite-affiliation-network-data-in-r/
# Toy data
```{r}
df <- data.frame( 
    person = c('Sam','Sam','Sam','Greg','Tom','Tom','Tom','Mary','Mary'), 
    group = c('a','b','c','a','b','c','d','b','d'), 
    stringsAsFactors = F)
df
```

```{r}
m <- table( df )
M <- as.matrix( m )
```
```{r}
library('Matrix')
A <- spMatrix(nrow=length(unique(df$person)),
ncol=length(unique(df$group)),
i = as.numeric(factor(df$person)),
j = as.numeric(factor(df$group)),
x = rep(1, length(as.numeric(df$person))) )
row.names(A) <- levels(factor(df$person))
colnames(A) <- levels(factor(df$group))
A
```

```{r}
Arow <- tcrossprod(A)
Arow
```

```{r}
Acol <- tcrossprod(t(A))
```
# Actual Data
```{r}
# Load the 'igraph' library
library('igraph')
# (1) Read in the data files, NA data objects coded as 'na'
magact96 = read.delim('https://solomonmg.github.io/assets/img/mag_act96.txt',
na.strings = 'na')
magact97 = read.delim('https://solomonmg.github.io/assets/img/mag_act97.txt',
na.strings = 'na')
magact98 = read.delim('https://solomonmg.github.io/assets/img/mag_act98.txt',
na.strings = 'na')
```

```{r}
classes_to_departments <- data.frame(class = c("Biostatistics","Islamic Civ", "Calc 1", "Linear Algebra", "Chemistry", "The Modern World-System", "Calc 2", "Social Networks", "Exile and Diaspora"), department = c("Math", "History", "Math", "Math", "Chemistry", "Sociology", "Math", "Sociology", "History"), stringsAsFactors = F)


classes_data <- data.frame(name = c("Leo", "Clement", "Palla", "Filippo"), class1 = c("Biostatistics","Islamic Civ", "Calc 1", "Linear Algebra"), class2 = c("Chemistry", "The Modern World-System", "Calc 2", "Social Networks"), class3 = c("Linear Algebra", "Exile and Diaspora", "Linear Algebra", "The Modern World-System"), stringsAsFactors = FALSE)

classes_data
classes_to_departments_matrix <- table(classes_to_departments)
class(classes_to_departments_matrix) <- "matrix"  


classesMatrix = table(classes_data)
class(classesMatrix) <- "matrix" # And we convert it from a table to a matrix

# View(classesMatrix)
people_to_departments <- t(classes_to_departments_matrix) %*% t(classesMatrix)
```

