---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(tidyverse, dplyr, stringr, rio, here)
```

```{r}
elite_data <- readRDS("elite_data.RDS")
fdi13_20 <- readRDS("fdi13_20.RDS")
```

```{r}
# use fdi2015 to predict seats in 2016

fdi13_20 %>% select(hometown, fdi_2015) %>% drop_na(fdi_2015) -> fdi15

elite_data %>% 
arrange(hometown) %>% 
  filter(term_serve == "16_21" & branch == "Government") %>% select(hometown) %>% add_count(hometown) %>% rename(num_seat = n) %>% distinct() -> seatgov16

fdi15 %>% 
  left_join(seatgov16) %>% mutate(num_seat = ifelse(is.na(num_seat), 0, num_seat)) %>%  rename(fdi = fdi_2015) -> model_data1

# t2 %>% 
#   left_join(t1) %>% drop_na() -> model_data2
# m0 <- lm(num_seat ~ fdi_2015, data = model_data2)
# summary(m0)
```

```{r}
# use fdi2020 to predict seats in 2021

fdi13_20 %>% select(hometown, fdi_2020) %>% drop_na(fdi_2020) -> fdi20

elite_data %>% 
arrange(hometown) %>% 
  filter(term_serve == "21_26" & branch == "Government") %>% select(hometown) %>% add_count(hometown) %>% rename(num_seat = n) %>% distinct() -> seatgov21

fdi20 %>% 
  left_join(seatgov21) %>% mutate(num_seat = ifelse(is.na(num_seat), 0, num_seat)) %>% rename(fdi = fdi_2020) -> model_data2 

# pulling all seat in term 16_21 and 21-26 together. FDI can't explain the variation of seats across hometown 

rbind(model_data1, model_data2) -> model_data6

m0 <- lm(num_seat ~ fdi, data = model_data6)
summary(m0)
```


