---
title: "Network"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
elite_data <- readRDS("elite_data.RDS")
```


# Compare terms' clusters 
```{r}
# filter for each term 
data <- elite_data %>% 
  filter(term_serve == "01_06") %>% drop_na(hometown) %>% 
  select(seatID, hometown, branch)

# ----------------
#method 1:   #convert to a matrix --> # Convert  matrix to an igraph object
# term9.mat <- as.matrix(term9)
# g <- graph.edgelist(term9.mat, directed = FALSE)
# plot(g)
#---------------

# method 2: make object from df 
term9 <- data %>% select(seatID, hometown)
term9.g <- graph.data.frame(term9, 
                            #vertices = df_vertex_attr,
                            directed = FALSE)
plot(term9.g)


# Count number of edges
gsize(term9.g) 
E(term9.g) # list all edges

# Count number of vertices
gorder(term9.g) #79
V(term9.g) # list all vertices
```

```{r}
# Create new vertex attribute called 'branch'
term9.g <- set_vertex_attr(term9.g, "branch", value = data$branch)

# View all vertex attributes 
vertex_attr(term9.g)                            

# View attributes of first five vertices in a dataframe
V(term9.g)[[1:5]]                              

# View edge attributes ???? 
edge_attr(term9.g)

# Find all edges that include hometown"thanh hoa"
E(term9.g)[[inc('thanh hoa')]] 
```

```{r}
# Set vertex color by branch
V(term9.g)$color <- ifelse(V(term9.g)$branch == "Politburo", "red", "blue") # why it fills color to hometown too?

# Add Node size as an attribute of vertice
V(term9.g)$node.size <- degree(term9.g)

# View all vertex attributes again 
vertex_attr(term9.g) 

# View edge attributes again : empty
edge_attr(term9.g)

# delete isolate 
#delete_vertices(simplify(term9.g), degree(g)==0)
```

```{r}
# plot
plot.igraph(term9.g, 
            vertex.size = 5*V(term9.g)$node.size, # size of hometown = proportional 
            #vertex.color = V(term9.g)$branch,
            #vertex.label = V(term9.g)$hometown,
            vertex.label = NA,
            vertex.label.color="black",
            vertex.label.font = 2, 
            vertex.label.cex=.7,
            vertex.label.dist = 1, # Space out distance between label and vertex
            vertex.frame.color="transparent",
            layout=layout_with_fr) 

# centralization level of the graph
centralization.degree(term9.g, normalized = T)
```

```{r}
d %>% select(positionID, hometown) %>% slice(1:30) -> d1
d.g <- graph.data.frame(d1)

#V(d.g)$type <- bipartite.mapping(d.g)$type

#V(d.g)$color <- ifelse(V(d.g)$type, "lightblue", "salmon")
#V(d.g)$shape <- ifelse(V(d.g)$type, "circle", "square")
#E(d.g)$color <- "lightgray"

plot.igraph(d.g, 
            layout=layout.fruchterman.reingold, 
            edge.arrow.size=.5,
            
            vertex.size = 5*V(term9.g)$node.size, # size of hometown = proportional 
            vertex.color = V(term9.g)$hometown,
            vertex.label = NA,
            vertex.label.color="black",
            vertex.label.font = 2, 
            vertex.label.cex=.7,
            vertex.label.dist = 1, # Space out distance between label and vertex
            vertex.label.degree = 1, # The position of the label in relation to the vertex
            vertex.frame.color="transparent",
            
            edge.color= "gray",
            edge.arrow.width=.1 # get rid of the arrow
)
            
```

# Bipartite
```{r}

g <- graph.data.frame(term9, directed = FALSE)

V(g)$type <- bipartite_mapping(g)$type

# Create new vertex attribute called 'branch', take the value of branch in data
g <- set_vertex_attr(g, "branch", value = data$branch)

V(g)$colorbranch <- ifelse(V(g)$branch == "Politburo", "red", "blue") #???? DOESNT work?

V(g)$color <- ifelse(V(g)$type, "lightblue", "salmon")
V(g)$shape <- ifelse(V(g)$type, "circle", "square") # circle = hometown, square = seat
E(g)$color <- "lightgray"

degree <- degree(g, mode = "all")

plot(g, 
     vertex.label.cex = 0.5, # lable of vertex size
     vertex.frame.color="transparent",
     #vertex.label = NA,
     vertex.label.dist = 1, 
     vertex.size = 5*degree,
     layout=layout.fruchterman.reingold
     )
title("Hometown structure, term 2001-2006")

```

```{r}

# View all vertex attributes again 
vertex_attr(g) 

# View edge attributes again 
edge_attr(g)

# show all edges to a certain vertex
incident(g, "thanh hoa")

# identify all neighbors of a vertex 
neighbors(g, 'thanh hoa')

# find starting vertex of all edges
head_of(g, E(g))


# delete vertices with only 1 degree ????
delete_vertices(g, V(g)['thanh hoa'])

centralization.degree(g, normalized = T)
```

# Function - Network & Centralization of each term 

```{r}
hometown_structure <- function(term){
# filter for each term 
data <- elite_data %>% 
  filter(term_serve == term) %>% drop_na(hometown) %>% 
  select(seatID, hometown, branch)

term0 <- data %>% select(seatID, hometown)
g <- graph.data.frame(term0, directed = FALSE)

V(g)$type <- bipartite_mapping(g)$type

# Create new vertex attribute called 'branch', take the value of branch in data
g <- set_vertex_attr(g, "branch", value = data$branch)

V(g)$colorbranch <- ifelse(V(g)$branch == "Politburo", "#FC8E62", "#71AB7E") #???? DOESNT work?

V(g)$color <- ifelse(V(g)$type, "#71AB7E", "#FC8E62")
V(g)$shape <- ifelse(V(g)$type, "circle", "square") # circle = hometown, square = seat
E(g)$color <- "lightgray"

degree <- degree(g, mode = "all")
par(mar = c(0, 0, 0, 0))
plot(g, 
     vertex.label.cex = 0.5, 
     vertex.frame.color="transparent",
     #vertex.label = NA,
     vertex.label.dist = 1.5, 
     vertex.size = 4*degree,
     layout = layout_nicely
     )
centrality <- centralization.degree(g, normalized = T)
#title(paste0(c("Term", term, "Network centralization:", round(centrality$centralization, 3))))
title(paste0(c("Term: ", term)))
}

hometown_structure("96_01")
hometown_structure("01_06")
hometown_structure("06_11")
hometown_structure("11_16")
hometown_structure("16_21")
hometown_structure("21_26")



centralization_all <- c(0.081, 0.061, 0.118, 0.078, 0.049, 0.081)
```

# Function - Network & Centralization of each branch 

```{r}
centralization_pol_byterm <- function(term){
# filter for each term 
data <- elite_data %>% 
  filter(branch == "Politburo") %>% 
  filter(term_serve == term) %>% drop_na(hometown) %>% 
  select(seatID, hometown, branch)

term0 <- data %>% select(seatID, hometown)
g <- graph.data.frame(term0, directed = FALSE)

V(g)$type <- bipartite_mapping(g)$type

# Create new vertex attribute called 'branch', take the value of branch in data
g <- set_vertex_attr(g, "branch", value = data$branch)

V(g)$colorbranch <- ifelse(V(g)$branch == "Politburo", "#FC8E62", "#71AB7E") #???? DOESNT work?

V(g)$color <- ifelse(V(g)$type, "#438D75", "#D8B366")
V(g)$shape <- ifelse(V(g)$type, "circle", "square") # circle = hometown, square = seat
E(g)$color <- "lightgray"

degree <- degree(g, mode = "all")
plot(g, 
     vertex.label.cex = 0.5, 
     vertex.frame.color="transparent",
     #vertex.label = NA,
     vertex.label.dist = 1, 
     vertex.size = 5*degree,
     layout=layout.fruchterman.reingold
     )
centrality <- centralization.degree(g, normalized = T)
title(paste0(c("Term", term, "Network centralization:", round(centrality$centralization, 3))))
}

centralization_pol_byterm("96_01")
centralization_pol_byterm("01_06")
centralization_pol_byterm("06_11")
centralization_pol_byterm("11_16")
centralization_pol_byterm("16_21")
centralization_pol_byterm("21_26")

centralization_pol <- c(0.047, 0.034, 0.074, 0.068, 0.03, 0.06)


```

```{r}
centralization_gov_byterm <- function(term){
# filter for each term 
data <- elite_data %>% 
  filter(branch != "Politburo") %>% 
  filter(term_serve == term) %>% drop_na(hometown) %>% 
  select(seatID, hometown, branch)

term0 <- data %>% select(seatID, hometown)
g <- graph.data.frame(term0, directed = FALSE)

V(g)$type <- bipartite_mapping(g)$type

# Create new vertex attribute called 'branch', take the value of branch in data
g <- set_vertex_attr(g, "branch", value = data$branch)

V(g)$colorbranch <- ifelse(V(g)$branch == "Politburo", "#FC8E62", "#71AB7E") #???? DOESNT work?

V(g)$color <- ifelse(V(g)$type, "#9279AA", "#EEEF88")
V(g)$shape <- ifelse(V(g)$type, "circle", "square") # circle = hometown, square = seat
E(g)$color <- "lightgray"

degree <- degree(g, mode = "all")
plot(g, 
     vertex.label.cex = 0.5, 
     vertex.frame.color="transparent",
     #vertex.label = NA,
     vertex.label.dist = 1, 
     vertex.size = 5*degree,
     layout=layout.fruchterman.reingold
     )
centrality <- centralization.degree(g, normalized = T)
title(paste0(c("Term", term, "Network centralization:", round(centrality$centralization, 3))))
}

centralization_gov_byterm("96_01")
centralization_gov_byterm("01_06")
centralization_gov_byterm("06_11")
centralization_gov_byterm("11_16")
centralization_gov_byterm("16_21")
centralization_gov_byterm("21_26")

terms <- c("96_01", "01_06", "06_11", "11_16", "16_21", "21_26")
year <- c(1996, 2001, 2006, 2011, 2016, 2021)
centralization_gov <- c(0.091, 0.066, 0.105, 0.073, 0.052, 0.084)
```

# Centralization 
```{r}
df_centralization <- tibble(terms, year, centralization_all, centralization_pol, centralization_gov)

df_centralization %>% 
  pivot_longer(cols = 3:5, 
               names_to = "centralization",
               values_to = "value") %>% 
  ggplot(aes(year, value, group = centralization))+
  geom_line(aes(color = centralization), size = 2) +
  annotate("text", x = 2020, y = 0.04, label = "Politburo") + 
  
  annotate("text", x = 2018, y = 0.08, label = "Government") + 
  annotate("text", x = 2020, y = 0.068, label = "Overall") + 
  
  labs(x = "", 
       y = "Centralization Degree", 
       title = "Degree of Centralization in Each Branch",
       caption = "Data calculated by Author") +
scale_color_brewer(palette = 3) +
  scale_x_discrete(limits = c(1996, 2001, 2006, 2011, 2016, 2021)) +
  theme_minimal() +
  theme(legend.position = "none")

```

# Overall network

```{r, fig.width=18, fig.height=10}
data_all <- elite_data %>% 
  select(seatID, hometown, branch) %>% add_count(hometown) %>% arrange(desc(n)) %>% 
  filter(n >=10) %>% drop_na(hometown)

data_g <- data_all %>% select(seatID, hometown)
g_all <- graph.data.frame(data_g, directed = FALSE)

V(g_all)$type <- bipartite_mapping(g_all)$type

# Create new vertex attribute called 'branch', take the value of branch in data
g_all <- set_vertex_attr(g_all, "branch", value = data$branch)

V(g_all)$colorbranch <- ifelse(V(g_all)$branch == "Politburo", "red", "blue") #???? DOESNT work?

V(g_all)$color <- ifelse(V(g_all)$type, "lightblue", "salmon")
V(g_all)$shape <- ifelse(V(g_all)$type, "circle", "square") # circle = hometown, square = seat
E(g_all)$color <- "lightgray"

degree <- degree(g_all, mode = "all")
plot(g_all, 
     vertex.label.cex = 2, 
     vertex.frame.color="transparent",
     #vertex.label = NA,
     #vertex.label.cex = 
     vertex.label.dist = 1, 
     vertex.size = degree,
     layout=layout.fruchterman.reingold
     )
centrality <- centralization.degree(g_all, normalized = T)
title(paste(c("Hometown structure all terms","Network centralization: ", round(centrality$centralization, 3))))
```




```{r}
g.degree <- degree(g)
table(g.degree)
hist(g.degree)
which.max(g.degree) # strange, why does ha noi have degree of 62?
```


```{r}
g.between <- betweenness(g, directed = FALSE)
hist(g.between)

# Create plot with vertex size determined by betweenness score
plot(g, 
     vertex.label = NA,
     edge.color = 'black',
     vertex.size = sqrt(g.between)+1,
     edge.arrow.size = 0.05,
     layout = layout_nicely(g))
```
