---
title: "Visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(tidyverse)
library(dplyr)
library(igraph)
library(ggplot2)
library(ggrepel)

d <- readRDS("elite_data.RDS")
```

# Overall 
```{r}

 d %>% 
  add_count(hometown) %>% arrange(desc(n)) %>% drop_na(hometown) %>% 
  mutate(hometown = fct_reorder(hometown, n)) %>% 
  filter(n >= 5) %>% 
  
  # how many province? # how many seats?
  select(hometown, n) %>% distinct() %>% 
  mutate(sum_n = sum(n))

ggplot(aes(hometown)) +
 geom_bar(fill="darkgreen", alpha=.8, width=.5) +
  coord_flip() +
  #facet_wrap(~branch)+
  labs(
    x = "",
    y= "Count of seats",
    title = "Hometowns originated at least 5 seats in the Politburo and the Government",
    subtitle = "1996 ~ 2022",
    caption = "Souce: Data collected by author"
  ) +
  theme_minimal()
  
```
# Seats by branches

```{r}
d %>% 
  add_count(hometown) %>% arrange(desc(n)) %>% drop_na(hometown) %>% 
  mutate(hometown = fct_reorder(hometown, n)) %>% 
  filter(n >= 5) %>% 
  
ggplot(aes(hometown)) +
 geom_bar(fill="darkgreen", alpha=.8, width=.5) +
  coord_flip() +
  facet_wrap(~branch)+
  labs(
    x = "",
    y= "Count of seats",
    title = "Hometowns originated at least 5 seats in each branch",
    subtitle = "1996 ~ 2022",
    caption = "Souce: Data collected by author"
  )  +
  theme_minimal()
```
# Five hometowns by terms & by branch

## Data for plots
```{r}
d_p <- d %>% 
  group_by(term_serve, hometown) %>% 
  add_count(hometown) %>% arrange(desc(n)) %>% drop_na(hometown) %>% 
  mutate(term_serve = as.factor(term_serve),
    hometown = fct_reorder(hometown, n)) %>% 
  filter(hometown %in% c("ha noi", "nam dinh", "nghe an", "ha tinh", "thanh hoa")) %>% 
  # use year_starting_term to have numeric year. term_serve is character, not displayed correct in x axis
  select(year_starting_term, n, term_serve, hometown, branch, person_name) %>% distinct()  

# how many the top 5 held?
d %>% select(hometown) %>% 
  add_count(hometown) %>% 
  arrange(desc(n)) %>% distinct() %>% slice(1:5) %>% mutate(sum_n = sum(n))

```


## Plots 
```{r}

d_p %>% 
  ggplot(aes(year_starting_term, n, group = hometown)) +
  geom_line(aes(color = hometown), size = 1.5) +
  
  # need to place the text lable separately to not be overlapping 
  geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "nam dinh"),
    aes(label = hometown, color = hometown,
        x = year_starting_term - 2))+
 
  geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "ha noi"),
    aes(label = hometown, color = hometown,
        x = 2010, 
        y = 8.5))+
  
  geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "nghe an"),
    aes(label = hometown, color = hometown,
        x = 2020, 
        y = 5))+
  
   geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "ha tinh"),
    aes(label = hometown, color = hometown,
        x = 2015, 
        y = 4))+
  
     geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "thanh hoa"),
    aes(label = hometown, color = hometown,
        x = 2020, 
        y = 2.5))+
  
   # geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "quang nam"),
   #  aes(label = hometown, 
   #      x = 2020, 
   #      y = 1))+
  
  labs(
    title = "Change in number of seats per hometown across 6 terms (1996 ~ 2022)",
    x = "Year",
    y = "Count of seats",
    caption = "Souce: Data collected by author"
  ) +
  guides(color = FALSE) +
scale_color_brewer(palette="Paired") +
  theme_minimal()

```

## explaining the above plot 
```{r}

#first pol term
d_p %>% filter(term_serve == "96_01") %>% 
  arrange(desc(n)) %>% 
  select(hometown, n) %>% distinct()

d_p %>% filter(term_serve == "01_06") %>% 
  arrange(desc(n)) %>% 
  select(hometown, n) %>% distinct()

d_p %>% filter(term_serve == "06_11") %>% 
  arrange(desc(n)) %>% 
  select(hometown, n) %>% distinct()
d_p %>% filter(term_serve == "11_16") %>% 
  arrange(desc(n)) %>% 
  select(hometown, n) %>% distinct()
d_p %>% filter(term_serve == "16_21") %>% 
  arrange(desc(n)) %>% 
  select(hometown, n) %>% distinct()
d_p %>% filter(term_serve == "21_26") %>% 
  arrange(desc(n)) %>% 
  select(hometown, n) %>% distinct()

```

```{r}


```

## Five hometowns across term by branches - line, facet 

```{r}

d_p %>% 
  ggplot(aes(year_starting_term, n, group = hometown)) +
  geom_line(aes(color = hometown), size = 1.5) +
  facet_wrap(~branch) +
  geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "nam dinh"),
    aes(label = hometown, color = hometown,
        x = year_starting_term - 2))+
 
  geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "ha noi"),
    aes(label = hometown, color = hometown,
        x = 2010, 
        y = 8))+
  
  geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "nghe an"),
    aes(label = hometown, color = hometown,
        x = 2020, 
        y = 5))+
  
   geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "ha tinh"),
    aes(label = hometown, color = hometown,
        x = 2015, 
        y = 4))+
  
     geom_text(data = d_p %>% filter(year_starting_term == 2021 & hometown == "thanh hoa"),
    aes(label = hometown, color = hometown,
        x = 2019, 
        y = 2))+
scale_color_brewer(palette="Paired") +
    labs(
    title = "Change in number of seats per hometown across 6 terms (1996 ~ 2022)",
    x = "Year",
    y = "Count of seats",
    caption = "Souce: Data collected by author"
  ) +
  guides(color = FALSE) +
  theme_minimal()
```


## Five hometowns across term by branches - col

```{r}
library(RColorBrewer)
d_p %>% 
  filter(branch == "Politburo") %>% 
  ggplot(aes(year_starting_term, n, group = hometown)) +
  geom_col(aes(fill = hometown), position = "dodge") +
  scale_color_brewer(palette = "Paired") +
  theme_minimal()
  

```


# Proportion of seat per term
```{r}
d_ggplot %>% 
  group_by(term_serve) %>% 
  add_count(hometown)
  mutate(hometown_prop = )
  
   d %>% 
  drop_na(hometown) %>% 
  group_by(term_serve, branch) %>% 
  add_count(term_serve) %>% 
  rename(seat_per_branch_term = n) %>% 
     ungroup() %>% 
     group_by(term_serve, branch) %>% 
     add_count(hometown) %>% 
     mutate(prop_hometown_seat = n/seat_per_branch_term)  

   
ggplot(aes(hometown, prop_hometown_seat)) +
 geom_col(fill="#69b3a2", alpha=.8, width=.4) +
  coord_flip() +
  facet_wrap(~term_serve)+
  labs(
    x = "",
    y= "Prop of seats",
    title = "Hometowns ...",
    subtitle = ""
  )  +
  theme_minimal()
```

#Age

```{r}
d %>% 
  ggplot(aes(year_working_left)) +
  geom_histogram(fill = "#7F5088", color = "white") +
  facet_grid(~branch) +
  labs(
    x = "Number of year left",
    y = "Number of people",
    title = "Distribution of number of working year left by the time a person starts the term",
    subtitle = "Retire age: 62 for men, 60 for women"
  ) +
  theme_minimal()
```

## Exceeded age term 11-16
```{r}
d %>% 
  arrange(year_working_left) %>% 
  filter(term_serve == "11_16") %>% 
  filter(year_working_left < 0) %>% 
  select(person_name, year_working_left, branch)
```

## Working year >= 10 in Government term 11_16

```{r}
d %>% 
  arrange(year_working_left) %>% 
  filter(term_serve == "11_16") %>%
  filter(branch == "Government") %>% 
  filter(year_working_left >= 10) %>% 
  select(person_name, year_working_left, branch, position) %>% distinct()
```

## Mean age each term
```{r}

d %>% 
  mutate(age_by_beginning_term = year_starting_term - year_birth) %>% 
  group_by(term_serve, branch) %>% 
  mutate(mean_age = mean(age_by_beginning_term, na.rm = TRUE)) %>% 
  select(term_serve, branch, mean_age) %>% distinct() %>% 
  
  ggplot(aes(term_serve, mean_age, group = branch)) +
  geom_line(aes(color = branch), size = 1.5) +
  labs(
    x = "Term", 
    y = "Age",
    title = "Average age of the member each term in the politburo and the government"
  ) +
  theme_minimal()

```

```{r}
# number of member in the same cohort
d %>% 
  #filter(term_serve == "11_16") %>% 
  filter(year_working_left <= 0) %>% 
  #select(person_name, year_to_retire, year_working_left, year_birth) %>% 
  ggplot(aes(year_working_left)) +
  geom_bar(fill = "#7F5088", color = "white") +
  facet_wrap(branch ~ term_serve, nrow = 2, ncol = 5) +
  labs(
    title = "Number of member exceeds working age limit at the beginning of each term"
  ) +
  theme_minimal()
```
